springload/draftjs_exporter

- docs/README.md
- draftjs_exporter/dom.py
- example.py
- setup.py
- tests/test_dom.py
- tests/test_exports.json
- tests/test_output.py
For the following reasons:
- BeautifulSoup4 and html5lib are already dependencies of wagtail, thus lowering the overall number of dependencies on the project
- lxml requires libxml2 and local compilation, whereas html5lib is 100% python
- lxml's documentation quality is quite poor
- To the extent of my knowledge, lxml doesn't support custom attributes (as BeautifulSoup's docs put it, html5lib's extreme leniency is an advantage)
Drawbacks:
- It is much slower.
- It's 2 dependencies instead of 1. Perhaps we could only use `html5lib`, but its has nearly no documentation.
> Replace lxml with BeautifulSoup4 and html5lib

- docs/README.md
- draftjs_exporter/wrapper_state.py
- example.py
- tests/test_constants.py
- tests/test_output.py
Fix for #18.
Allows the following markup:
<ul class="bullet-list">
<li>A list item (0)
<ul class="bullet-list">
<li>
<ul class="bullet-list">
<li>A list item (2)</li>
</ul>
</li>
</ul>
</li>
</ul>
```
<ul class="bullet-list">
<li>A list item (0)
<ul class="bullet-list">
<li>
<ul class="bullet-list">
<li>A list item (2)</li>
</ul>
</li>
</ul>
</li>
</ul>
```
> Add support for arbitrary nesting jumps. Fix #18

- draftjs_exporter/html.py
- draftjs_exporter/wrapper_state.py
- tests/test_output.py
- tests/test_wrapper_state.py
Tackles very specific markup where blocks have a non-zero depth, like:
<ul class="bullet-list">
<li>
<ul class="bullet-list">
<li>
<ul class="bullet-list">
<li>
A list item (2)
</li>
<li>
A list item (2)
</li>
</ul>
</li>
</ul>
</li>
</ul>
or 
<ul class="bullet-list">
<li>
<ul class="bullet-list">
<li>
<ul class="bullet-list">
<li>
A list item (2)
</li>
</ul>
</li>
<li>
A list item (1)
</li>
</ul>
</li>
</ul>
or
<ul class="bullet-list">
<li>
<ul class="bullet-list">
<li>
<ul class="bullet-list">
<li>
A list item (2)
</li>
</ul>
</li>
</ul>
</li>
<li>
A list item (0)
</li>
</ul>
> Add support for rare cases where blocks start with a non-zero depth

- CHANGELOG.md
- draftjs_exporter/entities.py
- draftjs_exporter/entity_state.py
- draftjs_exporter/html.py
- draftjs_exporter/style_state.py
- tests/test_entities.py
- tests/test_entity_state.py
- tests/test_exports.json
- tests/test_style_state.py
Addresses #19.
The previous way of inserting those nodes was a bit backwards. Now control is left to the user, similar to what React components do with the `children` prop.
```python
class Link:
def render(self, props):
data = props.get('data', {})
attributes = {}
for key in data:
attr = key if key != 'url' else 'href'
attributes[attr] = data[key]
return DOM.create_element('a', attributes, props['children'])
```
> Add support for children control in entity decorator API

- draftjs_exporter/defaults.py
- draftjs_exporter/dom.py
- draftjs_exporter/entity_state.py
- draftjs_exporter/html.py
- draftjs_exporter/options.py
- draftjs_exporter/wrapper_state.py
- example.py
- tests/test_options.py
- tests/test_wrapper_state.py
See https://github.com/springload/draftjs_exporter/issues/39
This change allows to specify element rendering in details, via following structure:
```python
class DirectSpeech:
def render(self, props):
data = props.get('data', {})
name = data.get('name', None)
return DOM.create_element(
'div',
{'some-attr': 'test'},
DOM.create_element('h3', {}, name))
parsed_text = json.loads(text)
exporter = HTML({
'block_map': {
'direct-speech': {
'element': DirectSpeech(),
'wrapper': 'h1',
},
'unstyled': {'element': 'div'},
},
})
text = exporter.render(parsed_text)
```
Things I like in this approach:
- it makes block data available to be used in components rendering;
- I think that it's also nice that the syntax is the same as for entity decorators components.
Things I **don't** like:
- children are …
> Add basic support for block-level data

- draftjs_exporter/wrapper_state.py
- tests/test_output.py
Fix for #55. The wrapper stack reset wasn't up to date, and for some reason this particular scenario is one of the rare cases where the behaviour would be incorrect.
> Fix block ordering with block components and wrapper. Fix #55

- .coveragerc
- .githooks/pre-commit
- .travis.yml
- CHANGELOG.md
- Makefile
- README.rst
- draftjs_exporter/command.py
- draftjs_exporter/composite_decorators.py
- draftjs_exporter/dom.py
- draftjs_exporter/entity_state.py
- draftjs_exporter/html.py
- draftjs_exporter/style_state.py
- draftjs_exporter/wrapper_state.py
- example.py
- setup.py
- tests/test_composite_decorators.py
- tests/test_dom.py
- tests/test_entity_state.py
- tests/test_exports.py
- tests/test_output.py
- tests/test_style_state.py
- tests/test_wrapper_state.py
- tox.ini
Not too big of a speed bump but good to take nonetheless. I would expect real-world content (where text is way more common than entities and styles) to see a higher speed up.
```sh
Before: 23420 23688
After: 16631 16344
```
> Performance refactorings

- draftjs_exporter/html.py
- tests/test_html.py
See #60. This will make it easier for us to interface with our new storage of empty fields in Django ORMed DBs.
> Add support for None content state in HTML.render

- CHANGELOG.md
- draftjs_exporter/__init__.py
🎉 
> This release is functionally identical to the previous one, `v0.9.0`.
The project has reached a high-enough level of stability to be used in production, and breaking changes will now be reflected via major version changes.
> Release v1.0.0

- draftjs_exporter/engines/html5lib.py
- draftjs_exporter/engines/lxml.py
Thanks to @BertrandBordage for the suggestion.
This is quite a straightforward performance improvement. The speedup isn't big, but the change is very simple so well worth it.
> Pre-compile regular expressions used in html5lib and lxml engines

- .githooks/deploy
- .githooks/pre-commit
- Makefile
- README.rst
- benchmark.py
- example.py
- setup.py
- tox.ini
Adds a new `benchmark.py` script that uses a large content sample from https://github.com/thibaudcolas/markov_draftjs (792 ContentStates, ±1000 entities and inline styles). Measures the speed like `example.py` does, as well as the memory consumption.
Fixes #65, fixes #66.
The memory profiling uses a module called `memory_profiler`. It comes with line-by-line profiling of functions (with the `@profile` decorator), as well as a CLI that measures the consumption of the whole script every N seconds and can plot the result.
Here is what is displayed at the moment, in the CI tests:
```
Line #    Mem usage    Increment   Line Contents
================================================
94     39.1 MiB      0.0 MiB   @profile
95                             def memory_consumption_run():
96     39.1 …
```
> Add benchmarking script with realistic content

- draftjs_exporter/engines/string.py
- tests/engines/test_engines_string.py
- tests/test_exports.json
Interestingly, there was no test for _that_! I've added some. This bug is easily reproducible on http://draftjs-exporter.herokuapp.com/:
The problem is that the `append_child` method checks if elements are already present by value rather than by reference, so if two elements have equal values (same type, same children, same   attributes) the subsequent ones will be skipped.
I initially changed the check so it would be by reference (`any(c is child for c in elt['children'])`), but that's ± 5% slower in the benchmark so instead I converted the dicts into class instances so the `in` operator looks at references.
> Fix string engine incorrectly skipping identical elements at the same depth level

- README.rst
- benchmark.py
- docs/example.md
- draftjs_exporter/composite_decorators.py
- draftjs_exporter/defaults.py
- draftjs_exporter/dom.py
- example.py
- tests/test_composite_decorators.py
- tests/test_defaults.py
- tests/test_dom.py
- tests/test_entities.py
- tests/test_entity_state.py
- tests/test_exports.py
- tests/test_output.py
- tests/test_wrapper_state.py
Fixes #73.
- Removing this makes the exporter 5-10% faster.
- There is only one way to make those React-like "components", which simplifies the API.
- Composite decorators are now defined in a way that feels very similar to Draft.js. The only difference is that the strategy is a regex only, not an arbitrary function that can use a regex.
- All of the examples now use snake_case when naming those components.
This is a breaking change. I'll further document upgrade considerations in the changelog when this is merged.
> Remove support for class decorators, with new API for composite decorators

- benchmark.py
- draftjs_exporter/dom.py
- draftjs_exporter/html.py
- draftjs_exporter/utils/module_loading.py
- example.py
- tests/__init__.py
- tests/test_dom.py
- tests/test_exports.py
- tests/test_output.py
- tests/utils/test_module_loading.py
Fixes #64. This doesn't introduce any breaking changes I think. The `import_string` code (and tests) are from Django 2.0 (so without six), with the exception of the `raise ... from` syntax.
I was wondering whether to remove the `"html5lib"`, `"lxml"`, `"string"` shorthands but I'm not sure this would have any benefit except making the code simpler (and that would be a breaking change).
> Use dotted-path loading for custom backing engines (#64)

- README.rst
- draftjs_exporter/html.py
- setup.py
- tests/test_composite_decorators.py
- tests/test_dom.py
- tests/test_html.py
- tests/test_output.py
- tests/test_style_state.py
- tests/test_wrapper_state.py
Fixes #79. Last missing bit for the 2.0.0 release.
Some tests were failing because the `render` method was used incorrectly. There wasn't any test for what engine would be the "default", and I also added one other missing tests.
Apart from the tests, this is also updating relevant docs, and adding a `draftjs_exporter[html5lib]` install extra.
> Change default engine to the new dependency-free one introduced in #77

- CHANGELOG.md
- draftjs_exporter/html.py
Style & entity ranges processing (conversion from potentially overlapping ranges to nested styles) is one of the most complicated parts of the exporter. Bypassing it completely for blocks that do not contain styles nor entities greatly improves the performance for real-world content, which is mostly text-only.
As an example, [our real-world benchmark content](https://github.com/thibaudcolas/markov_draftjs) has 5650 blocks, 204 of which have styles, and 942 of which have entities (with some potential overlap). Even with no overlap, it means 80% of the content will benefit from this change.
----
`make dev` demo:
```sh
7074 function calls (6745 primitive calls)
6207 function calls (5878 primitive calls)
```
`make benchmark`:
```sh
801431 function calls (757891 primitive calls) in 0.563 …
```
> Improve performance by bypassing costly style/entity processing for text-only blocks

- CHANGELOG.md
- draftjs_exporter/composite_decorators.py
- draftjs_exporter/dom.py
- draftjs_exporter/html.py
- draftjs_exporter/style_state.py
- draftjs_exporter/wrapper_state.py
- example.py
- tests/test_composite_decorators.py
- tests/test_style_state.py
- tests/test_wrapper_state.py
Fixes #87, and more.
Style renderers now have access to the following props:
```python
{
'block': {...},
'blocks': [...],
'inline_style_range': {
'style': 'BOLD',
},
}
```
Ideally I would have wanted to add the full style range (with offset and length), but this can wait.
Composite decorators have access to:
```python
{
'match': {...},
'block': {...},
'blocks': [...],
}
```
Finally, block renderers also get access to more data:
Data:
```python
{
'block': {...},
'blocks': [...],
}
```
There is a special case where the full `block` won't be given – when the renderer is used to create an intermediary node when there is nesting involved:
```html
<ul>
<li>Full data</li>
<li>
<ul><li>Full data</li><ul/>
</li>
</ul>
```
In the example above, the `li` that contain text correspond to two blocks of …
> Provide more props for block, decorator, and style components

- .travis.yml
- CHANGELOG.md
- README.md
- docs/README.md
- setup.py
- tests/engines/test_engines_differences.py
- tox.ini
Fixes #75.
The only user-facing changes are:
- The new upper version bound for lxml, which wasn't defined before.
- The new upper version bound for html5lib, which used to be lower (now that htm5lib has been released with good version numbers).
This PR also updates the tox environments, as described in #75.
> Improve dependencies compatibility definition, and testing. Fix #75

- .github/CONTRIBUTING.md
- CHANGELOG.md
- Makefile
- README.md
- docs/README.md
- draftjs_exporter/__init__.py
- setup.py
Changelog: 
* Add upper bound to lxml dependency, now defined as `lxml>=3.6.0,<5` ([#75](https://github.com/springload/draftjs_exporter/issues/75)).
* Update html5lib upper bound, now defined as `html5lib>=0.999,<=1.0.1`.
This also introduces a proper Markdown description for the PyPI project's page 🎉(https://github.com/wagtail/wagtail/pull/4372#discussion_r177637239).
> Release v2.1.1

- setup.py
Should fix #98. `io.open` is available in both Python 2.7 and 3, and as an `encoding` option.
> Use io.open with utf-8 encoding in setup.py. Fix #98

- CHANGELOG.md
- draftjs_exporter/__init__.py
*  Use io.open with utf-8 encoding in setup.py. Fix [#98](https://github.com/springload/draftjs_exporter/issues/98) ([#99](https://github.com/springload/draftjs_exporter/pull/99))
> Release v2.1.2

- .github/CONTRIBUTING.md
- .travis.yml
- CHANGELOG.md
- setup.py
- tox.ini
This is just adding the version to the CI test matrix after trying it locally.
It seems to work fine on my computer (Python 3.7.0-a1, macOS 10.13, lxml 4.1.1), but it fails in CI (Python 3.7.0a4+, Ubuntu Trusty, lxml 4.1.1) because of one "differences between engines" test:
```
self.assertEqual(DOM_LXML.render_debug(DOM_LXML.parse_html('<p>Invalid < " > &</p>')), '<p>Invalid &lt; " &gt; &amp;</p>')
AssertionError: '<p>Invalid  &amp;</p>' != '<p>Invalid &lt; " &gt; &amp;</p>'
- <p>Invalid  &amp;</p>
+ <p>Invalid &lt; " &gt; &amp;</p>
```
That’s only lxml code here (`html.fromstring`), so it's either an issue there or in Python 3.7. I'll wait for the beta / RC release to be available on pyenv and in Travis before pursuing this further.
---
I just noticed the recent [3.7.0-b1 …
> Add support for Python 3.7

- CHANGELOG.md
- draftjs_exporter/__init__.py
* Increase lower bound of optional lxml dependency to v4.2.0 to guarantee Python 3.7 support ([#88](https://github.com/springload/draftjs_exporter/pull/88)).
> Release v2.1.3

- .github/CONTRIBUTING.md
- Makefile
- setup.py
Small changes I made during investigating #103 
- `make publish-test` command added to push to test pypi
- `make sdist` command added to share the build command
- uses `rm dist/* ; python setup.py sdist` instead of `rm dist/* && python setup.py sdist` because `rm` may fail if `dist/` directory empty
- use `with open` to close `README.md` file
> upload to test pypi command and small tweaks

- draftjs_exporter/engines/string.py
- draftjs_exporter/entity_state.py
- draftjs_exporter/html.py
Most of those improvements are fairly small. They amount to skipping operations that are not necessary in simple / more common content patterns – for example, blocks not having any styles or entities, or entities not containing anything beyond text.
The speed gain is about 8%. There also seems to be a 20% decrease in memory consumption.
Before:
```
python benchmark.py
Exporting 792 ContentStates 500 times
303087001 function calls (281316001 primitive calls) in 159.333 seconds
```
After:
```
python benchmark.py
Exporting 792 ContentStates 500 times
261211501 function calls (247228001 primitive calls) in 146.123 seconds
```
> Minor performance improvements

- CHANGELOG.md
- draftjs_exporter/__init__.py
* Minor performance improvements (8% speed-up, 20% lower memory consumption) ([#108](https://github.com/springload/draftjs_exporter/pull/108))
* Fix export bug with adjacent entities - the exporter moved their contents outside of the entities' markup ([#106](https://github.com/springload/draftjs_exporter/pull/106), [#107](https://github.com/springload/draftjs_exporter/pull/107)). Thanks to [@ericpai](https://github.com/ericpai) for reporting this.
> Release v2.1.5

- CHANGELOG.md
- draftjs_exporter/html.py
- draftjs_exporter/wrapper_state.py
- example.py
- tests/test_html.py
I'm having an issue where DraftJS will generate blocks with no `depth` key at times, for example
```json
{
"blocks": [{
"key": "fvkqt",
"text": "hello world",
"type": "unstyled",
"inlineStyleRanges": [],
"entityRanges": [],
"data": {}
}],
"entityMap": {}
}
```
and parts of this library that assume a `depth` key to be present choke.
Perhaps this is a bug in the client library (I'm on 0.10.5), but I thought I'd open a PR anyway as I'd really like to resolve the issue quickly :sweat_smile: 
Thanks for putting together this library, it could really accelerate development of some features we're working on :slightly_smiling_face:
> Assume block depth of 0 if not specified

- CHANGELOG.md
- draftjs_exporter/html.py
- tests/test_html.py
Small (± 5%) speed bump for text-only blocks
> Implement small performance improvements identified from #110

- CHANGELOG.md
- draftjs_exporter/__init__.py
* Assume same block defaults as Draft.js would when attributes are missing: depth = 0, type = unstyled, no entities, no styles ([#110](https://github.com/springload/draftjs_exporter/pull/110)).
* Assume same block defaults as Draft.js would when attributes are missing: depth = 0, type = unstyled, no entities, no styles ([#110](https://github.com/springload/draftjs_exporter/pull/110), thanks to [@tpict](https://github.com/tpict)).
> Release v2.1.6

- tox.ini
Travis shows failures since lxml 4.4.0 has been released, because of Python 3.4 support being removed and changes to how attributes are sorted in 3.7.
https://travis-ci.org/springload/draftjs_exporter/builds
> Reduce tested versions of lxml to remove flaky tests

- CHANGELOG.md
- draftjs_exporter/command.py
- draftjs_exporter/constants.py
- draftjs_exporter/engines/string.py
- draftjs_exporter/entity_state.py
- draftjs_exporter/html.py
- draftjs_exporter/options.py
- draftjs_exporter/style_state.py
- draftjs_exporter/wrapper_state.py
- setup.py
- tests/test_command.py
- tests/test_entity_state.py
- tests/test_options.py
- tests/test_output.py
- tests/test_style_state.py
- tests/test_wrapper_state.py
This contains a few refactorings that should bring some performance improvements, mostly thanks to [`__slots__`](https://stackoverflow.com/questions/472000/usage-of-slots).
The other main improvement is to move the calculation of options for blocks/types/styles to the initialisation of the exporter instead of the rendering.
All in all this makes the exporter about 10% faster, and reduces memory consumption by 20-50% (hard to measure).
> Small performance improvements with __slots__ and more

- .travis.yml
- docs/CONTRIBUTING.md
Updates from 3.8-dev to 3.8 (3.8.0) now that Python 3.8 has officially been released. Also switches over to Ubuntu 18 for Python 3.5 – I thought it wasn’t available but it’s on the list on https://docs.travis-ci.com/user/languages/python/.
---
- ~[ ] Consider adding unit tests, especially for bug fixes. If you don't, tell us why.~
- ~[ ] Consider updating documentation. If you don't, tell us why.~
> Finish setting up Python 3.8 stable testing

- .travis.yml
- docs/README.md
- draftjs_exporter/entity_state.py
- draftjs_exporter/html.py
- example.py
- setup.py
- tests/test_entity_state.py
Fixes #91, in a non-breaking way.
Entity components now have access to the following data under `props['entity']`:
```python
props['entity'] = {
'type': entity_details['type'],
'mutability': entity_details['mutability'] if 'mutability' in entity_details else None,
'block': block,
'blocks': blocks,
'entity_range': {
'key': self.completed_entity,
},
}
```
I’ve also documented the shortcomings of the current implementation in the Troubleshooting docs. Addressing this would require breaking changes so I think it’s relatively unlikely to happen.
---
> Add more data for entity components (#91)

- CHANGELOG.md
- draftjs_exporter/__init__.py
This release contains breaking changes. **Be sure to check out the "how to upgrade" section below.**
* Remove support for Python 2.7 and 3.4 ([#111](https://github.com/springload/draftjs_exporter/issues/111), [#120](https://github.com/springload/draftjs_exporter/pull/120)).
* Add support for Python 3.8.
* Small performance improvements by using lists’ mutable `.sort()` instead of `sorted()`, which is a bit faster. (±2% faster) ([#120](https://github.com/springload/draftjs_exporter/pull/120)).
* Add [PEP-484](https://www.python.org/dev/peps/pep-0484/) type annotations for the project’s public APIs ([#101](https://github.com/springload/draftjs_exporter/issues/101), [#123](https://github.com/springload/draftjs_exporter/pull/123)).
* Add [PEP-561](https://www.python.org/dev/peps/pep-0561/) …
> Release v3.0.0

- .gitignore
- draftjs_exporter/composite_decorators.py
- draftjs_exporter/dom.py
- draftjs_exporter/html.py
- draftjs_exporter/wrapper_state.py
- tests/test_composite_decorators.py
Changes block rendering to:
- Bypass styles rendering when there are no styles defined on the given block
- Bypass composite decorators rendering for the most common case of using `<br/>` alone
Before:
```
$ BENCHMARK_RUNS=100 make benchmark
python benchmark.py
Exporting 792 ContentStates 100 times
48263701 function calls (45467001 primitive calls) in 29.696 seconds
Ordered by: cumulative time
List reduced from 71 to 10 due to restriction <10>
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
79200    0.918    0.000   29.696    0.000 html.py:55(render)
565000    2.569    0.000   21.452    0.000 html.py:86(render_block)
565000    1.274    0.000    8.137    0.000 wrapper_state.py:99(element_for)
79200    0.045    0.000    6.486    0.000 dom.py:119(render)
1049100/79200 …
```
> Small performance improvements per block

- CHANGELOG.md
- draftjs_exporter/__init__.py
* Add `Typing :: Typed` trove classifier to the package.
* Small performance improvements (1.5x faster) for blocks that do not have inline styles, and configurations that only use `\n -> <br/>` composite decorators. ([#127](https://github.com/springload/draftjs_exporter/pull/127))
> Release v3.0.1

- CHANGELOG.md
- draftjs_exporter/__init__.py
This release contains breaking changes. **Be sure to check out the "how to upgrade" section below.**
- Remove support for Python 3.5 ([#129](https://github.com/springload/draftjs_exporter/pull/129))
- Remove HTML attributes alphabetical sorting of default string engine ([#129](https://github.com/springload/draftjs_exporter/pull/129))
- Disable single and double quotes escaping outside of attributes for string engine ([#129](https://github.com/springload/draftjs_exporter/pull/129))
- Stop sorting inline styles alphabetically ([#129](https://github.com/springload/draftjs_exporter/pull/129))
Do not upgrade to this version if you are using the exporter in Python 3.5. Please keep using [v3.0.1](https://github.com/springload/draftjs_exporter/tree/v3.0.1) of the exporter.
The default `string` …
> Release v4.0.0

- Makefile
- docs/CONTRIBUTING.md
fixes #132 
The primary purpose of this PR is to add an `make bdist_wheel` command to build a python wheel archive. This task is included in both the `make publish` and `make publish-test` commands and does not replace source distributions.
I've added a `make clean-dist` command to clean the dist folder. This command is ran before publishing to make sure we have a clean dist folder.
- not applicable.
- two failed tests but probably related to my dev environment (python 3.8.3, fedora 32)
- FAIL: test_export_lxml_big_content_export (tests.test_exports.TestExportsLXML)
- FAIL: test_export_lxml_entity_with_data-* (tests.test_exports.TestExportsLXML)
- check! ✅
- Python 3.8; Linux Fedora 32
> Add wheel build option

- .travis.yml
- Makefile
- docs/CONTRIBUTING.md
- example.py
- setup.py
- tox.ini
This updates the library’s test suite and package metadata to check for Python [3.9 support](https://docs.python.org/3.9/whatsnew/3.9.html). No code changes needed – but there were a few deprecation warnings in `html5lib`, and in the example code. This should make it easier to support Python 3.10 in late 2021.
---
- ~[ ] Consider adding unit tests, especially for bug fixes. If you don't, tell us why.~ N/A
> Tentative support for Python 3.9

- CHANGELOG.md
- draftjs_exporter/__init__.py
- setup.py
- tox.ini
- Add support for Python 3.9 ([#134](https://github.com/springload/draftjs_exporter/pull/134)).
- Update html5lib upper bound, now defined as `html5lib>=0.999,<2`, to ensure compatibility with Python 3.10 ([#134](https://github.com/springload/draftjs_exporter/pull/134)).
> Release v4.1.1

- README.md
- draftjs_exporter/dom.py
- draftjs_exporter/engines/string_compat.py
- tests/engines/test_engines_string_compat.py
- tests/test_exports.json
- tests/test_exports.py
This introduces a new `string_compat` / `draftjs_exporter.engines.string_compat.DOMStringCompat` engine, which is a copy of the existing `string` engine with two changes added for backwards compatibility:
- Reverts _Remove HTML attributes alphabetical sorting of default string engine ([#129](https://github.com/springload/draftjs_exporter/pull/129))_.
- Reverts _Disable single and double quotes escaping outside of attributes for string engine ([#129](https://github.com/springload/draftjs_exporter/pull/129))_.
Both of those changes were introduced in v4.0.0, I think they make complete sense for projects using the exporter since, but they do change the output. It’s important for the output to be as stable as possible in a lot of scenarios, so I made sure to document how to preserve the …
> Add new "string_compat" engine for maximum output stability

- README.md
- benchmark.py
Replace `logging.warn` (deprecated in [Python 2.7, 2011](https://github.com/python/cpython/commit/04d5bc00a219860c69ea17eaa633d3ab9917409f)) with `logging.warning` (added in [Python 2.3, 2003](https://github.com/python/cpython/commit/6fa635df7aa88ae9fd8b41ae42743341316c90f7)).
* https://docs.python.org/3/library/logging.html#logging.Logger.warning
* https://github.com/python/cpython/issues/57444
---
Replacing deprecated function with one which has been around since 2.3.
Not big enough for docs.
macOS / Python 3.10
Thanks for contributing to this project!
> Replace deprecated logging.warn with logging.warning
